services:
  devcontainer:
    image: "mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  tailscale:
    image: tailscale/tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    restart: unless-stopped
    network_mode: service:devcontainer
    volumes:
      - "/dev/net/tun:/dev/net/tun"
      - tailscale-data:/var/lib/tailscale
    environment:
      TS_HOSTNAME: "triapprend-tailscale"
      TS_SOCKS5_SERVER: ":1055"
      TS_OUTBOUND_HTTP_PROXY_LISTEN: ":1080"
      TS_EXTRA_ARGS: "--exit-node=100.70.168.22 --exit-node-allow-lan-access --shields-up"

volumes:
  tailscale-data:
